# springboot
server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
    settings:
      web-allow-others: true
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:~/data/h2/auth_db;AUTO_SERVER=TRUE
    username: test  # 사용자 이름 (로그인 시 사용)
    password: 1234  # 사용자 암호 (로그인 시 사용)
    driver-class-name: org.h2.Driver

  jpa:
    atabase-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update # 해당의미?
    showSql: true

security:
  oauth2:
    jwt:
      signkey: 123@#$

logging:
  level:
    org:
      springframework:
        security: debug
        boot: debug