# springboot
server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
    settings:
      web-allow-others: true
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:~/data/h2/auth_db;AUTO_SERVER=TRUE
    username: test  # 사용자 이름 (로그인 시 사용)
    password: 1234  # 사용자 암호 (로그인 시 사용)
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update # 해당의미?
    showSql: true

security:
  oauth2:
    jwt:
      signkey: 123@#$

# 인증서버 관련 커스텀 설정
common:
  # token-type : JWT or BEARER
  token-type: JWT
  client-id: testClientId
  client-secret: testSecret
  client-server-url: http://localhost:8081/client/authorization



logging:
  level:
    org:
      springframework:
        security: debug
        boot: debug